package main.gui;

import javax.swing.*;
import java.awt.*;
import main.service.AdminService;
import main.gui.AdminDashboard;

public class ReportFrame extends JFrame {

    // This text area is the main display area of the screen.
    // Whenever the admin clicks a report button, the generated report text appears here.
    JTextArea outputArea;

    // AdminService contains the real business logic for reports and offers.
    // This frame only collects input from the user and shows the result on the screen.
    AdminService adminService;

    public ReportFrame() {
        // Create the service object once, so all buttons can reuse it.
        adminService = new AdminService(); 

        // Basic window setup: title, size, close behavior, and layout style.
        setTitle("Admin Reports & Offers");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // The top panel holds the navigation and action buttons.
        // BorderLayout.NORTH places this panel at the top of the frame.
        JPanel panel = new JPanel();

        // Each button represents one action the admin can perform from this screen.
        JButton productBtn = new JButton("Product Report");
        JButton categoryBtn = new JButton("Category Report");
        JButton profitBtn = new JButton("Profit Report");
        JButton offerBtn = new JButton("Add Offer");

        // Back button returns the user to the admin dashboard.
        JButton backBtn = new JButton("Back");

        // Add buttons from left to right in the panel.
        panel.add(backBtn);
        panel.add(productBtn);
        panel.add(categoryBtn);
        panel.add(profitBtn);
        panel.add(offerBtn);

        // Add the finished button panel to the top part of the window.
        add(panel, BorderLayout.NORTH);

        // The center area displays reports in a scrollable text box.
        // It is read-only because reports should be generated by the system, not typed by the admin.
        outputArea = new JTextArea();
        outputArea.setEditable(false);

        // A monospaced font keeps columns and numbers easier to read in report output.
        outputArea.setFont(new Font("Courier New", Font.PLAIN, 12));

        // JScrollPane allows long reports to be viewed without resizing the window.
        add(new JScrollPane(outputArea), BorderLayout.CENTER);


        // When Back is clicked, return to the admin dashboard and close this report window.
        backBtn.addActionListener(e -> {
            new AdminDashboard();
            dispose();
        });

        // When the product report button is clicked, show the product summary.
        productBtn.addActionListener(e -> {
            outputArea.setText(adminService.generateProductReport());
        });

        // When the category report button is clicked, show category counts.
        categoryBtn.addActionListener(e -> {
            outputArea.setText(adminService.generateCategoryReport());
        });

        // When the profit report button is clicked, show the profit statistics.
        profitBtn.addActionListener(e -> {
            outputArea.setText(adminService.generateProfitReport());
        });

        // This button starts a small step-by-step form using dialog boxes.
        // The admin enters the product, discount, and date range for the offer.
        offerBtn.addActionListener(e -> {
            // Ask for the product ID first because the offer must belong to an existing product.
            String idText = JOptionPane.showInputDialog(this, "Enter Product ID:");

            // If the admin presses Cancel, stop the process quietly.
            if (idText == null) return;

            // Remove extra spaces so input like "  5  " is accepted as "5".
            idText = idText.trim();

            // Empty input is not useful, so show a clear validation message.
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Product ID is required.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            int productId;
            try {
                // Convert the text to an integer because product IDs are stored as numbers.
                productId = Integer.parseInt(idText);
            } catch (NumberFormatException ex) {
                // If conversion fails, the admin typed something that is not a valid whole number.
                JOptionPane.showMessageDialog(this,
                        "Product ID must be a valid integer.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Before asking for more details, make sure the product actually exists.
            if (!adminService.productExists(productId)) {
                JOptionPane.showMessageDialog(this,
                        "No product found with ID " + productId + ".",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ask for the discount percentage after the product ID is confirmed.
            String discountText = JOptionPane.showInputDialog(this, "Enter Discount %:");

            // Cancel means the admin changed their mind, so stop without showing an error.
            if (discountText == null) return;

            // Trim spaces before checking or converting the discount value.
            discountText = discountText.trim();

            // A discount cannot be calculated from an empty value.
            if (discountText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Discount is required.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            double discountValue;
            try {
                // Use double so discounts such as 12.5 can be accepted.
                discountValue = Double.parseDouble(discountText);
            } catch (NumberFormatException ex) {
                // This catches values like "abc" or "ten", which cannot be used in calculations.
                JOptionPane.showMessageDialog(this,
                        "Discount must be a valid number.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Keep the discount in a sensible range before saving the offer.
            if (discountValue < 1 || discountValue > 100) {
                JOptionPane.showMessageDialog(this,
                        "Discount must be between 1 and 100.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ask for the offer start date.
            // The service will handle deeper date validation if needed.
            String start = JOptionPane.showInputDialog(this, "Start Date:");
            if (start == null) return;
            start = start.trim();

            // The start date is required so the system knows when the offer begins.
            if (start.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Start date is required.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ask for the offer end date.
            String end = JOptionPane.showInputDialog(this, "End Date:");
            if (end == null) return;
            end = end.trim();

            // The end date is required so the offer does not stay active forever by mistake.
            if (end.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "End date is required.",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                // All simple checks passed, so send the offer details to the service layer.
                adminService.addOffer(productId, discountValue, start, end);

                // Let the admin know the operation completed successfully.
                JOptionPane.showMessageDialog(this, "Offer Applied Successfully!");
            } catch (IllegalArgumentException ex) {
                // Expected validation errors from the service are shown clearly to the admin.
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                // Any unexpected problem is still handled so the application does not crash.
                JOptionPane.showMessageDialog(this,
                        "Unable to apply offer: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        // Show the window after all components and button actions have been prepared.
        setVisible(true);
    }
}
